import Head from "next/head"
import dynamic from "next/dynamic"
import {
  Box,
  Heading,
  Text,
  Flex,
  Grid,
  keyframes,
  Button,
} from "@chakra-ui/react"
import GsapContext from "../store/gsap-context"
import useIsomorphicLayoutEffect from "../components/hooks/useIsomorphicLayoutEffect"
import { useContext } from "react"
import NextImage from "next/image"
import Marquee from "react-fast-marquee"
import SlideShowSection from "../components/SlideshowSection"
import { SectionHeading, SectionParagraph } from "../components/ui/SectionText"
import ContactSection from "../components/ContactSection"
import HeroSection from "../components/HeroSection"
import AboutUsSection from "../components/AboutUsSection"
import Footer from "../components/ui/Footer"
import React from "react"

const MessageSection = dynamic(() =>
  import("../components/MessageSectionAnimation")
)

const grainAnimation = keyframes`
  0%, 100% { transform:translate(0, 0); }
  10% { transform:translate(-5%, -10%); }
  20% { transform:translate(-15%, 5%); }
  30% { transform:translate(7%, -25%); }
  40% { transform:translate(-5%, 25%); }
  50% { transform:translate(-15%, 10%); }
  60% { transform:translate(15%, 0%); }
  70% { transform:translate(0%, 15%); }
  80% { transform:translate(3%, 35%); }
  90% { transform:translate(-10%, 10%); }
`

const animation = `${grainAnimation} 8s steps(10) infinite`

const MarqueeSection = () => (
  <Marquee gradient={false}>
    <Heading
      fontWeight="black"
      color="brand.300"
      fontSize={["5rem", "10rem"]}
      mr="3rem"
      opacity="0.25"
      overflowY="hidden"
    >
      EXQUISITE WOOD FLOORS
    </Heading>
  </Marquee>
)

const Home = (props) => {
  return (
    <Box
      as="main"
      _before={{
        animation: animation,
        backgroundImage: "url(/images/noise.png)",
        content: "''",
        height: "300%",
        left: "-50%",
        opacity: "0.5",
        position: "fixed",
        top: "-110%",
        width: "300%",
        zIndex: "-10",
        overflow: "hidden",
      }}
      zIndex="0"
      pos="relative"
    >
      <Head>
        <title>Exquisite Wood Floors</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeroSection />
      <MarqueeSection />
      <AboutUsSection />
      <MessageSection />
      <SlideShowSection />
      <ContactSection />
      <Footer bgColor="brand.100" />
    </Box>
  )
}

export default Home
